### ISSUE TITLE
Exclude based on label

### ISSUE THREAD

**Issue by Ineluctable** [omaralvarez/deluge-autoremoveplus#1]
Is there any way you could code in a way to exclude torrents based on their label?

For example, I'd like to keep all torrents labeled with "save", regardless of the tracker's URL, even if they meet the criteria for deletion.
## 

I'm not sure if it matters, but I'm using the built-in 'Label' plugin for the labels.

Thanks either way!

**Comment by omaralvarez** [comment]
Yes, I think it certainly is possible. Although next I will work on some
core features for deluge, so don't expect the new feature soon, but I like
your idea. I will add it to the list of features for the next version.

2015-02-24 8:00 GMT+01:00 Ineluctable notifications@github.com:

**Comment by wjbeckett** [comment]
I'd love to see this feature too!
Would be really helpful.

**Comment by jmf866** [comment]
Just adding my vote for this feature.  Exclude or include based on label.

**Comment by ghost** [comment]
Hey,
Just noticed this topic. I asked for the same thing on the official forum !
You got my vote too !

**Comment by ghost** [comment]
Nice to got news from you.
If we can help you, feel free.

**Comment by dgw** [comment]
Would also be great to only process torrents with a label in a specified set. e.g. I use the 'downloaded' label to mark files after copying them off the server to my machine, and 'downloaded-seed-complete' for things that have been confirmed seeding long enough. Would be super useful in combination with #6 and #3 if implemented.

**Comment by ghost** [comment]
Hey @omaralvarez,

I just think about all enhancements listed (exclude some labels, include only some labels, ...)
May be the better solution to develop it is 
- to add in the dropdownlist 2 new items (EXCLUDE, ONLY).
- if these items are selected, display a dropdown of existing label instead of seetime

exemple: (Seedtime = 7.0 AND label = tv) OR (ratio = 1.5 AND label = movies) AND (exclude=seed,music)

and after the real improvment will to be able to combine query like with bracets () and let user custom edit it : https://github.com/omaralvarez/deluge-autoremoveplus/issues/7

**Comment by omaralvarez** [comment]
Thanks for all the suggestions, I will take this into consideration, although I'm not sure if @raspdealer's idea would be confusing for people that are already used to how the plugin works. Although I do like your #7 idea.

I think in the future there will be an advanced mode in which you can create advanced text queries like the ones you mention, but it will be optional.

**Comment by ghost** [comment]
You're right.
Don't forget all users with a basic need!

**Comment by ghost** [comment]
thanks
