### ISSUE TITLE
Global rules still apply after disabling

### ISSUE THREAD

**Issue by kade-robertson** [omaralvarez/deluge-autoremoveplus#39]
Hello,

I was using this plugin to help clean up torrents for a specific tracker, so I set up the global rules with exemptions for every other tracker. However, I decided instead to use the tracker-specific rules instead, so I moved the rules there, and then removed everything from the exemption list, disabled everything else and saved. On the next scan, it deleted about 600GB of data it shouldn't, probably because of what the old global settings were. Why weren't these settings cleared? I even cleared them manually again, and just now it's removed more things that fit the old rules which don't exist anymore.

The old global settings were to delete anything with a ratio above 1 and a seedtime above 2 days.

**Comment by omaralvarez** [comment]
Hey!

First of all, let me say I am really sorry that you lost data due to this issue. As I have mentioned, in other issues, I no longer have time to work on the plugin due to work, PhD and other time consuming tasks. Since this is a pretty big issue, I will try to make an exception and take a look into it. No promises on a timeframe though. Just a heads up, you can set impossible general rules, like seed for 10 years, so nothing gets deleted while I take a look. 

Were you using the WebUI or GTK? Have you double checked that the config was loading correctly and the contents of the config file were correct? Could you try deleting egg, config and reconfiguring from scratch from GTK UI? Backup everything before trying anything.

Again, sorry for the lost data.

**Comment by kade-robertson** [comment]
Thanks for getting back to me! I totally understand being busy, no worries there.

I was using the plugin through GTK, I'm not totally sure where the config file is stored. Currently the plugin is totally uninstalled though, not sure if that removes it or I have to find it manually. Does the plugin make any log files that might be of use as well?
