### ISSUE TITLE
Threshold for removing torrents based on Seed count

### ISSUE THREAD

**Issue by cron410** [omaralvarez/deluge-autoremoveplus#4]
I personally like to leave torrents seeding until the end of time if they have less than 5 seeders. I've been going over the code but cannot wrap my head around how it works. All we would need is a user defined variable and a function to compare the torrent's current number of seeders to the variable and not remove it if the seeders are less than that variable. I'll have my sister look at it while she learns python. She's more of a programmer and I more of a sysadmin.

Also, I do not know how to label this issue. Maybe the maintainer has to do it himself?

**Comment by omaralvarez** [comment]
Yes, I have to label the issue, don't worry about it. 

About your issue, right now the code is a little har to understand. I have to document it properly, although what you are asking I think can be done, I don't know if a python newbie would be able to do it easily. You would need to define a new compare function, modify some Gtk code and some JS code. I certainly can help, or do it myself if you guys prefer. I'm going to try to update the plugin in late september or early november with label support and this, since for me it would be easy and I think it is a worthwhile upgrade.

**Comment by cron410** [comment]
Awesome thanks. Ill keep track of my progress here. I'll also try to get
some pull requests from people on HN and reddit.

GTK seems easy to code (or was it QT?). The code is difficult to understand
for a newbie, but I'll keep at it. This is probably the last piece in the
puzzle for fully automating Deluge and the postprocessing of videos in my
setup.

**Comment by omaralvarez** [comment]
Support for this feature is added in 4a2e64082dd6abe19fdf975576abaa33d51e3786.
