### ISSUE TITLE
Can't remove the second condition line

### ISSUE THREAD

**Issue by ghost** [omaralvarez/deluge-autoremoveplus#8]
I have 2 condition lines but I can't remove the second one.
So I need to put the exact same value as the first one.

**Comment by omaralvarez** [comment]
Yes, right now this is a limitation that can be circumvented in the way you mention. The default value already has no effect in practice, since the minimum value it has is 0 and it will always be true. So the result will depend only on the first criteria that the user introduces (age will always be greater than 0). 

I guess I could implement a button to add and remove conditions, but I think there are more important functionalities that need to be addressed first, and this would be a substantial change in the UI.

**Comment by ghost** [comment]
I agree.
I will look the code to see if I can help.

**Comment by omaralvarez** [comment]
Thanks a lot, right now the code needs a lot of comments and a big refactor so it can be more easily understood :smile: . As I add new features I will try to improve on these aspects.

**Comment by omaralvarez** [comment]
This is done, one can now remove every condition if desired.
